use graphoxide_core::{Confidence, Extraction};
use graphoxide_extract::extract;
use std::fs;
use tempfile::TempDir;

fn fixture(extension: &str, source: &str) -> Extraction {
    let temp = TempDir::new().unwrap();
    let path = temp.path().join(format!("sample.{extension}"));
    fs::write(&path, source).unwrap();
    extract(&path).unwrap()
}

fn rationale_labels(extraction: &Extraction) -> Vec<&str> {
    extraction
        .nodes
        .iter()
        .filter(|node| node.file_type == "rationale")
        .map(|node| node.label.as_str())
        .collect()
}

#[test]
fn test_module_docstring_extracted() {
    let result = fixture(
        "py",
        r#""""This module handles authentication because legacy sessions were insecure."""
def login(): pass
"#,
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("authentication")));
}

#[test]
fn test_function_docstring_extracted() {
    let result = fixture(
        "py",
        r#"def process():
    """We use chunked processing here because the full dataset exceeds RAM."""
    pass
"#,
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("chunked")));
}

#[test]
fn test_class_docstring_extracted() {
    let result = fixture(
        "py",
        r#"class Cache:
    """Chosen over Redis because we need zero external dependencies in the test env."""
    pass
"#,
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("Redis")));
}

#[test]
fn test_rationale_comment_extracted() {
    let result = fixture(
        "py",
        "def build():\n    # NOTE: must run before compile() or linker will fail\n    pass\n",
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("NOTE")));
}

#[test]
fn test_rationale_for_edges_present() {
    let result = fixture(
        "py",
        r#""""Module docstring explaining the why."""
def foo():
    """Function docstring with rationale."""
    pass
"#,
    );
    assert!(result
        .edges
        .iter()
        .any(|edge| edge.relation == "rationale_for"));
}

#[test]
fn test_short_docstring_ignored() {
    let result = fixture("py", "def foo():\n    \"\"\"Constructor.\"\"\"\n    pass\n");
    assert!(rationale_labels(&result).is_empty());
}

#[test]
fn test_rationale_confidence_is_extracted() {
    let result = fixture(
        "py",
        r#""""This module exists because we needed a standalone parser."""
def parse(): pass
"#,
    );
    assert!(result
        .edges
        .iter()
        .filter(|edge| edge.relation == "rationale_for")
        .all(|edge| edge.confidence == Confidence::Extracted));
}

#[test]
fn test_alembic_module_docstring_suppressed() {
    let result = fixture(
        "py",
        r#""""initial schema

Revision ID: 0001abcd
Revises:
Create Date: 2023-01-01 00:00:00
"""
revision = "0001abcd"
down_revision = None
def upgrade(): pass
def downgrade(): pass
"#,
    );
    assert!(!rationale_labels(&result)
        .iter()
        .any(|label| label.contains("Revision ID")));
}

#[test]
fn test_alembic_function_docstrings_still_extracted() {
    let result = fixture(
        "py",
        r#""""Revision ID: 0002 Revises: 0001"""
revision = "0002"
down_revision = "0001"
def upgrade():
    """Add users table because auth was added in this release."""
    pass
def downgrade(): pass
"#,
    );
    let labels = rationale_labels(&result);
    assert!(!labels.iter().any(|label| label.contains("Revision ID")));
    assert!(labels.iter().any(|label| label.contains("auth")));
}

#[test]
fn test_non_migration_revision_var_not_suppressed() {
    let result = fixture(
        "py",
        r#""""This module tracks document revisions because we need audit history."""
revision = 42
def get_revision(): pass
"#,
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("audit history")));
}

#[test]
fn test_django_migration_module_docstring_suppressed() {
    let result = fixture(
        "py",
        r#""""Add post_priority_config table."""
from django.db import migrations
class Migration(migrations.Migration):
    dependencies = [("myapp", "0001_initial")]
    operations = []
"#,
    );
    assert!(!rationale_labels(&result)
        .iter()
        .any(|label| label.contains("post_priority")));
}

#[test]
fn test_generated_file_module_docstring_suppressed() {
    let result = fixture(
        "py",
        r#""""Generated by the protocol buffer compiler. DO NOT EDIT!"""
from google.protobuf import descriptor as _descriptor
class UserMessage: pass
"#,
    );
    assert!(!rationale_labels(&result)
        .iter()
        .any(|label| label.to_ascii_lowercase().contains("protocol buffer")));
}

#[test]
fn test_decorated_method_node_id_is_class_qualified() {
    let result = fixture(
        "py",
        r#"class Bar:
    @property
    def baz(self) -> int:
        """Return the baz value because callers expect a cached integer."""
        return 1
    @staticmethod
    def helper() -> int:
        """A static helper documented for downstream callers."""
        return 2
    @classmethod
    def factory(cls) -> "Bar":
        """Construct a Bar via the canonical classmethod entry point."""
        return cls()
    def normal(self) -> int:
        """A normal instance method documented for comparison."""
        return 3
"#,
    );
    let ids = result
        .nodes
        .iter()
        .map(|node| (node.label.as_str(), node.id.as_str()))
        .collect::<std::collections::BTreeMap<_, _>>();
    let node_ids = result
        .nodes
        .iter()
        .map(|node| node.id.as_str())
        .collect::<std::collections::BTreeSet<_>>();
    for name in ["baz", "helper", "factory", "normal"] {
        let label = format!(".{name}()");
        let id = ids
            .get(label.as_str())
            .unwrap_or_else(|| panic!("missing method {label}: {ids:?}"));
        assert!(id.ends_with(&format!("_bar_{name}")), "{id}");
        assert!(result.edges.iter().any(|edge| {
            edge.relation == "rationale_for"
                && edge.target == **id
                && node_ids.contains(edge.source.as_str())
        }));
    }
    let graph = graphoxide_graph::build_graph(std::slice::from_ref(&result)).unwrap();
    for node in result
        .nodes
        .iter()
        .filter(|node| node.file_type == "rationale")
    {
        assert!(graph.nodes.iter().any(|built| built.id == node.id));
        assert!(graph
            .links
            .iter()
            .any(|edge| edge.source == node.id || edge.target == node.id));
    }
}

fn assert_word_boundary(source: &str, label: &str) {
    assert!(label.chars().count() <= 80, "{label}");
    let core = label.strip_suffix('…').unwrap_or(label).trim_end();
    assert!(source.starts_with(core), "{source:?} / {label:?}");
    if core != source {
        assert!(matches!(
            source[core.len()..].chars().next(),
            Some(' ') | None
        ));
    }
}

#[test]
fn test_long_docstring_label_truncates_on_word_boundary() {
    let doc = "This routine reconciles pending settlement batches nightly because upstream feeds arrive unordered and out of sequence.";
    let result = fixture(
        "py",
        &format!("def reconcile_batches():\n    \"\"\"{doc}\"\"\"\n    pass\n"),
    );
    assert_word_boundary(doc, rationale_labels(&result)[0]);
}

#[test]
fn test_docstring_newline_and_indentation_collapsed_to_single_space() {
    let result = fixture(
        "py",
        r#"def sync_inventory():
    """Aggregates daily settlement counts for reconciliation runs.
       Retries three times before raising to the monitoring pipeline.
    """
    pass
"#,
    );
    let label = rationale_labels(&result)[0];
    assert!(!label.contains('\n'));
    assert!(!label.contains("  "));
    assert!(label.contains("runs. Retries"));
}

#[test]
fn test_truncated_docstring_never_ends_with_bare_period() {
    let doc = "Loads the merchant configs bundle from disk once at process start-up and caches. It refreshes every six hours in the background.";
    let result = fixture(
        "py",
        &format!("def load_merchant_config():\n    \"\"\"{doc}\"\"\"\n    pass\n"),
    );
    let label = rationale_labels(&result)[0];
    assert!(label.len() < doc.len());
    assert!(!label.ends_with('.'));
    assert!(label.ends_with('…'));
}

#[test]
fn test_docstring_opening_with_unbroken_long_token_keeps_content() {
    let url = format!(
        "https://example.com/api/v3/settlements/{}/confirm",
        "a".repeat(60)
    );
    let doc = format!("{url} documents the retry contract for this handler.");
    let result = fixture(
        "py",
        &format!("def call_endpoint():\n    \"\"\"{doc}\"\"\"\n    pass\n"),
    );
    let label = rationale_labels(&result)[0];
    assert!(!matches!(label, "" | "…"));
    assert!(label.starts_with("https://example.com/"));
}

#[test]
fn test_short_docstring_label_unchanged() {
    let doc = "Splits the bearer token because some clients send a stray prefix.";
    let result = fixture(
        "py",
        &format!("def parse_token():\n    \"\"\"{doc}\"\"\"\n    pass\n"),
    );
    assert_eq!(rationale_labels(&result), [doc]);
}

#[test]
fn test_js_rationale_comment_extracted() {
    let result = fixture(
        "ts",
        "// NOTE: must run before compile() or the linker will fail\nexport function build(): void {}\n",
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("NOTE")));
}

#[test]
fn test_js_block_comment_rationale_extracted() {
    let result = fixture(
        "ts",
        "/**\n * WHY: retries are capped because the upstream rate-limits at 10 rps.\n */\nexport function fetchData(): void {}\n",
    );
    assert!(rationale_labels(&result)
        .iter()
        .any(|label| label.contains("rate-limits")));
}

#[test]
fn test_js_adr_reference_extracted() {
    let result = fixture(
        "ts",
        "// Gateway pattern per ADR-0002; provider selection per ADR-0015.\nexport function route(): void {}\n",
    );
    let labels = result
        .nodes
        .iter()
        .filter(|node| node.file_type == "doc_ref")
        .map(|node| node.label.as_str())
        .collect::<std::collections::BTreeSet<_>>();
    assert_eq!(
        labels,
        std::collections::BTreeSet::from(["ADR-0002", "ADR-0015"])
    );
    assert_eq!(
        result
            .edges
            .iter()
            .filter(|edge| edge.relation == "cites")
            .count(),
        2
    );
}

#[test]
fn test_js_adr_reference_normalized_and_deduped() {
    let result = fixture(
        "ts",
        "// See ADR-11 for the trust boundary.\n// ADR 0011 also governs containment.\nexport function guard(): void {}\n",
    );
    let labels = result
        .nodes
        .iter()
        .filter(|node| node.file_type == "doc_ref")
        .map(|node| node.label.as_str())
        .collect::<Vec<_>>();
    assert_eq!(labels, ["ADR-0011"]);
}

#[test]
fn test_js_adr_in_string_literal_not_extracted() {
    let result = fixture("ts", "export const banner = \"compliant with ADR-0099\";\n");
    assert!(!result.nodes.iter().any(|node| node.file_type == "doc_ref"));
}

#[test]
fn test_js_rationale_label_truncates_on_word_boundary() {
    let comment = "retries are capped because the upstream billing service enforces a strict per-tenant rate limit that keeps dropping requests";
    let full = format!("WHY: {comment}");
    let result = fixture(
        "ts",
        &format!("// {full}\nexport function fetchData(): void {{}}\n"),
    );
    assert_word_boundary(&full, rationale_labels(&result)[0]);
}

#[test]
fn test_js_rationale_label_never_ends_with_bare_period_when_truncated() {
    let comment = "retries are capped at five attempts before the circuit breaker opens for the endpoint. A metrics counter records every trip.";
    let full = format!("WHY: {comment}");
    let result = fixture(
        "ts",
        &format!("// {full}\nexport function fetchData(): void {{}}\n"),
    );
    let label = rationale_labels(&result)[0];
    assert!(label.len() < full.len());
    assert!(!label.ends_with('.'));
}

#[test]
fn test_js_rationale_comment_opening_with_unbroken_long_token_keeps_content() {
    let url = format!(
        "https://example.com/api/v3/settlements/{}/confirm",
        "a".repeat(60)
    );
    let result = fixture(
        "ts",
        &format!(
            "// WHY: {url} documents the retry contract for this handler.\nexport function fetchData(): void {{}}\n"
        ),
    );
    let label = rationale_labels(&result)[0];
    assert!(!matches!(label, "" | "…"));
    assert!(label.starts_with("WHY:"));
}

#[test]
fn test_js_short_rationale_comment_unchanged() {
    let expected = "NOTE: must run before compile() or the linker will fail";
    let result = fixture(
        "ts",
        &format!("// {expected}\nexport function build(): void {{}}\n"),
    );
    assert_eq!(rationale_labels(&result), [expected]);
}
